# Generated by Django 5.2 on 2025-05-07 19:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('search_title', ckeditor.fields.RichTextField(blank=True)),
                ('facebook', models.TextField(blank=True)),
                ('twitter', models.TextField(blank=True)),
                ('linkedin', models.TextField(blank=True)),
                ('instagram', models.TextField(blank=True)),
                ('youtube', models.TextField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('footer', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
