# Generated by Django 5.2 on 2025-05-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='search_title',
        ),
    ]
