# Generated by Django 5.2 on 2025-05-09 17:13

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('qualification', ckeditor.fields.RichTextField(blank=True)),
                ('facebook', models.TextField(blank=True)),
                ('twitter', models.TextField(blank=True)),
                ('linkedin', models.TextField(blank=True)),
                ('pinterest', models.TextField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('information', ckeditor.fields.RichTextField(blank=True)),
                ('review', ckeditor.fields.RichTextField(blank=True)),
                ('photo_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
