# Generated by Django 5.2 on 2025-05-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='description',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='information',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='list_date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='pinterest',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='review',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='twitter',
        ),
    ]
