# Generated by Django 5.2 on 2025-05-09 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_remove_listing_description_remove_listing_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_1',
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='facebook',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='linkedin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='pinterest',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='qualification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='twitter',
            field=models.TextField(blank=True),
        ),
    ]
